name: Build Test for Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_unit_test_blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Configure Hexo Unit Test
        run: |
          git clone https://github.com/hexojs/hexo-theme-unit-test.git ~/unit_test
          mkdir -p ~/unit_test/themes/SoSimple
          cp -r ./* ~/unit_test/themes/SoSimple/
          cd ~/unit_test/themes/SoSimple
          pnpm i
          cd /home/runner/work/hexo-theme-sosimple/hexo-theme-sosimple
          cp ./_config.example.yml ~/unit_test/themes/SoSimple/_config.yml
          cp ./.github/assets/hexo_config.yml ~/unit_test/_config.yml
          cp ./.github/assets/_posts/* ~/unit_test/source/_posts/
          cd ~/unit_test
          npm install
          npm install hexo-renderer-pug --save
          npx hexo new "SoSimple简介"
          cat /home/runner/work/hexo-theme-sosimple/hexo-theme-sosimple/README.md >> ./source/_posts/SoSimple简介.md

      - name: Generate Test # 生成 Hexo 单元测试
        run: |
          cd ~/unit_test
          npx hexo generate --bail
